#!/bin/bash

SCRIPTS_DIR=$(dirname $(readlink -e "$0"))
ROOT_DIR=$(dirname "$SCRIPTS_DIR")

cd "$ROOT_DIR" && while inotifywait -r -e modify,create,delete --include '.*\.py$' .; do "$SCRIPTS_DIR/test"; done
