name: CI checks
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          version-file: .tool-versions
      - run: uv audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          version-file: .tool-versions
      - run: ./scripts/check-code

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          version-file: .tool-versions
      - run: ./scripts/check-format

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          version-file: .tool-versions
      - run: ./scripts/test
